# Generated by Django 4.1.7 on 2023-03-31 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('designation_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.profile')),
                ('parent', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='complainapp.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('registered_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('response_date', models.DateField(default=datetime.datetime(2023, 4, 1, 11, 47, 37, 807854))),
                ('completed', models.BooleanField(default=False)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.profile')),
                ('registered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.designation')),
            ],
        ),
    ]
