# Generated by Django 4.1.7 on 2023-04-02 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='response_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 11, 0, 8, 758472)),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_holder', to='complainapp.profile'),
        ),
    ]
