# Generated by Django 4.1.7 on 2023-04-05 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complainapp', '0003_alter_complain_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='response_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 14, 34, 24, 100157)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complainapp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.complain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
