# Generated by Django 4.1.7 on 2023-04-05 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complainapp', '0004_alter_complain_response_date_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='response_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 16, 29, 57, 643243)),
        ),
    ]
