# Generated by Django 4.1.7 on 2023-04-05 16:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complainapp', '0007_remove_comments_parent_alter_complain_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='postlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='response_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 16, 58, 40, 642955)),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
