# Generated by Django 4.1.7 on 2023-04-05 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complainapp', '0009_alter_complain_response_date_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='response_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 17, 49, 56, 401798)),
        ),
    ]
